[package]
name = "df-raw-lookup"
version = "0.1.1"
edition = "2021"
authors = [
    "Nicholas Westerhausen <nick@westmail.cc>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8"
encoding_rs_io = "0.1"
regex = "1.5"
rouille = "3"
slug = "0.1"
serde_json = "1.0"
walkdir = "2"

[dependencies.clap]
version = "3"
default-features = true
features = ["derive"]

[dependencies.phf]
version = "0.10"
default-features = true
features = ["macros"]

[dependencies.serde]
version = "1"
default-features = true
features = ["derive"]
