[package]
name = "df-raw-lookup"
version = "0.1.1"
edition = "2021"
authors = [
    "Nicholas Westerhausen <nick@westmail.cc>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.5"
slug = "^0.1"
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"
encoding_rs = "^0.8"
encoding_rs_io = "^0.1"
clap = { version = "^3.0", features = ["derive"] }
walkdir = "2"
rouille = "3"