[package]
name = "df-raw-lookup"
version = "0.1.0"
edition = "2021"
authors = [
    "Nicholas Westerhausen <nick@westmail.cc>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1"
slug = "^0"
serde = {version = "^1", features = ["derive"]}
serde_json = "^1"
encoding_rs = "^0"
encoding_rs_io = "^0"